In [2]:
import numpy as np

u = np.linspace(-2, 2, 6)
v = np.linspace(-1, 1, 4)

# Generate 2-D arrays from u and v: X, Y
X,Y = np.meshgrid(u,v)

In [17]:
print(u)
print(X)
print("")
print(v)
print(Y)

[-2.  -1.2 -0.4  0.4  1.2  2. ]
[[-2.  -1.2 -0.4  0.4  1.2  2. ]
 [-2.  -1.2 -0.4  0.4  1.2  2. ]
 [-2.  -1.2 -0.4  0.4  1.2  2. ]
 [-2.  -1.2 -0.4  0.4  1.2  2. ]]

[-1.         -0.33333333  0.33333333  1.        ]
[[-1.         -1.         -1.         -1.         -1.         -1.        ]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 1.          1.          1.          1.          1.          1.        ]]


In [3]:
a = np.array([7921,5184,8836,4761])
a.mean()

6675.5

In [4]:
r = a.max() - a.min()
b = a - a.mean()

In [5]:
b = b/ r

In [6]:
b

array([ 0.30564417, -0.36601227,  0.53018405, -0.46981595])