In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2, include_bias=True)

test = np.array([
    [2, 3],
    [2, 4]
])

pf.fit(test)
print("Size of train", test.shape)
print(test)
x = pf.transform(test)
print("Size of train", x.shape)
print(x)

df = pd.DataFrame(x)
df.columns = pf.get_feature_names()
df.head()

Size of train (2, 2)
[[2 3]
 [2 4]]
Size of train (2, 6)
[[  1.   2.   3.   4.   6.   9.]
 [  1.   2.   4.   4.   8.  16.]]


1   x0   x1  x0^2  x0 x1  x1^2
0  1.0  2.0  3.0   4.0    6.0   9.0
1  1.0  2.0  4.0   4.0    8.0  16.0